### ISSUE TITLE
Addon won't install

### ISSUE THREAD

**Issue by Nobosaur** [brianhornsby/plugin.audio.tuneinradio#80]
Hi,
I'm using OSMC- lattest version on Raspberry Pi, I tried to install from zip file and from repo but addon won't install, do you have some idea why is this?

**Comment by walterc1991** [comment]
I am having the same issue. After downloading the SuperRepo the TuneIn Add-On appears under my Music Add-Ons list but upon attempting to download it comes up saying Installation Failed

**Comment by walterc1991** [comment]
11:27:44 T:123145309356032  NOTICE: virtual bool CAESinkDARWINOSX::Initialize(AEAudioFormat &, std::string &): Opening default device Built-in Output
11:28:05 T:140735198531584  NOTICE: Log level changed to "LOG_LEVEL_DEBUG_FREEMEM"
11:28:05 T:140735198531584  NOTICE: Enabled debug logging due to GUI setting. Level 2.
11:28:05 T:140735198531584   DEBUG: ------ Window Init () ------
11:28:08 T:140735198531584   DEBUG: ProcessMouse: trying mouse action leftclick
11:28:08 T:140735198531584   DEBUG: Activating window ID: 10050
11:28:09 T:140735198531584   DEBUG: ------ Window Deinit (SettingsCategory.xml) ------
11:28:09 T:140735198531584   DEBUG: ------ Window Init (EventLog.xml) ------
11:28:09 T:140735198531584   DEBUG: CGUIMediaWindow::GetDirectory (events://)
11:28:09 T:140735198531584   DEBUG:   ParentPath = [events://]
11:28:09 T:123145305063424   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/ImageLib-x86-osx.so)
11:28:09 T:123145305063424   DEBUG: Loading: /Applications/Kodi.app/Contents/Resources/Kodi/system/ImageLib-x86-osx.so
11:28:10 T:140735198531584   DEBUG: ProcessMouse: trying mouse action leftclick
11:28:10 T:140735198531584   DEBUG: ------ Window Init (DialogAddonInfo.xml) ------
11:28:12 T:140735198531584   DEBUG: ProcessMouse: trying mouse action leftclick
11:28:12 T:140735198531584   DEBUG: CFileCache::Open - opening <v7/addons/plugin.audio.tuneinradio/plugin.audio.tuneinradio-2.0.5.zip.md5> using cache
11:28:12 T:140735198531584   DEBUG: CurlFile::Open(0x7fa29806c960) http://redirect.superrepo.org/v7/addons/plugin.audio.tuneinradio/plugin.audio.tuneinradio-2.0.5.zip.md5
11:28:12 T:140735198531584    INFO: easy_aquire - Created session to http://redirect.superrepo.org
11:28:12 T:140735198531584   DEBUG: CCurlFile::Open - effective URL: <http://mirrors.fe.up.pt/superrepo/v7/addons/plugin.audio.tuneinradio/plugin.audio.tuneinradio-2.0.5.zip.md5>
11:28:12 T:123145304526848   DEBUG: Thread FileCache start, auto delete: false
11:28:12 T:123145304526848    INFO: CFileCache::Process - Hit eof.
11:28:12 T:123145304526848   DEBUG: Thread FileCache 123145304526848 terminating
11:28:12 T:140735198531584   DEBUG: ------ Window Deinit (DialogAddonInfo.xml) ------
11:28:13 T:123145309892608   DEBUG: CurlFile::Open(0x7fa291d272a0) http://redirect.superrepo.org/v7/addons/plugin.audio.tuneinradio/plugin.audio.tuneinradio-2.0.5.zip
11:28:13 T:123145309892608   DEBUG: CCurlFile::Open - effective URL: <http://mirrors.fe.up.pt/superrepo/v7/addons/plugin.audio.tuneinradio/plugin.audio.tuneinradio-2.0.5.zip>
11:28:17 T:140735198531584   DEBUG: ------ Window Deinit (Pointer.xml) ------
11:28:20 T:123145309892608   ERROR: CAddonInstallJob[plugin.audio.tuneinradio]: invalid package special://home/addons/packages/plugin.audio.tuneinradio-2.0.5.zip
11:28:20 T:140735198531584   DEBUG: CGUIMediaWindow::GetDirectory (events://)
11:28:20 T:140735198531584   DEBUG:   ParentPath = []
11:28:20 T:140735198531584   DEBUG: CGUIMediaWindow::GetDirectory (events://)
11:28:20 T:140735198531584   DEBUG:   ParentPath = [events://]
11:28:20 T:140735198531584   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
11:28:21 T:140735198531584   DEBUG: Keyboard: scancode: 0x35, sym: 0x001b, unicode: 0x001b, modifier: 0x0
11:28:21 T:140735198531584   DEBUG: OnKey: escape (0xf01b) pressed, action is PreviousMenu
11:28:21 T:140735198531584   DEBUG: CGUIWindowManager::PreviousWindow: Deactivate
11:28:21 T:140735198531584   DEBUG: ------ Window Deinit (EventLog.xml) ------
11:28:21 T:140735198531584   DEBUG: CGUIWindowManager::PreviousWindow: Activate new
11:28:21 T:140735198531584   DEBUG: ------ Window Init (SettingsCategory.xml) ------
11:28:22 T:140735198531584   DEBUG: ------ Window Init (Pointer.xml) ------
11:28:24 T:140735198531584   DEBUG: Keyboard: scancode: 0x35, sym: 0x001b, unicode: 0x001b, modifier: 0x0
11:28:24 T:140735198531584   DEBUG: OnKey: escape (0xf01b) pressed, action is PreviousMenu
11:28:24 T:140735198531584   DEBUG: CGUIWindowManager::PreviousWindow: Deactivate
11:28:24 T:140735198531584   DEBUG: ------ Window Deinit (Pointer.xml) ------
11:28:24 T:140735198531584   DEBUG: ------ Window Deinit (SettingsCategory.xml) ------
11:28:24 T:140735198531584   DEBUG: CGUIWindowManager::PreviousWindow: Activate new
11:28:24 T:140735198531584   DEBUG: ------ Window Init (Settings.xml) ------
11:28:25 T:140735198531584   DEBUG: ------ Window Init (Pointer.xml) ------
11:28:25 T:140735198531584   DEBUG: ------ Window Deinit (DialogKaiToast.xml) ------
11:28:26 T:140735198531584   DEBUG: Keyboard: scancode: 0x35, sym: 0x001b, unicode: 0x001b, modifier: 0x0
11:28:26 T:140735198531584   DEBUG: OnKey: escape (0xf01b) pressed, action is PreviousMenu
11:28:26 T:140735198531584   DEBUG: CGUIWindowManager::PreviousWindow: Deactivate
11:28:26 T:140735198531584   DEBUG: ------ Window Deinit (Pointer.xml) ------
11:28:26 T:140735198531584   DEBUG: ------ Window Deinit (Settings.xml) ------
11:28:26 T:140735198531584   DEBUG: CGUIWindowManager::PreviousWindow: Activate new
11:28:26 T:140735198531584   DEBUG: ------ Window Init (Home.xml) ------
11:28:27 T:140735198531584   DEBUG: ------ Window Init (Pointer.xml) ------
11:28:28 T:140735198531584   DEBUG: ProcessMouse: trying mouse action leftclick
11:28:28 T:140735198531584   DEBUG: Activating window ID: 10001
11:28:28 T:140735198531584   DEBUG: ------ Window Deinit (Home.xml) ------
11:28:28 T:140735198531584   DEBUG: ------ Window Init (MyPrograms.xml) ------
11:28:28 T:140735198531584   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/executable)
11:28:28 T:140735198531584   DEBUG:   ParentPath = [addons://sources/executable/]
11:28:28 T:123145305600000   DEBUG: Thread BackgroundLoader start, auto delete: false
11:28:28 T:123145305600000   DEBUG: Thread BackgroundLoader 123145305600000 terminating
11:28:30 T:140735198531584   DEBUG: ProcessMouse: trying mouse action leftclick
11:28:30 T:123145305600000   DEBUG: Thread LanguageInvoker start, auto delete: false
11:28:30 T:123145305600000    INFO: initializing python engine.
11:28:30 T:123145305600000   DEBUG: CPythonInvoker(34, /Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log/addon.py): start processing
11:28:30 T:123145305600000   DEBUG: -->Python Interpreter Initialized<--
11:28:30 T:123145305600000   DEBUG: CPythonInvoker(34, /Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log/addon.py): the source file to load is "/Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log/addon.py"
11:28:30 T:123145305600000   DEBUG: CPythonInvoker(34, /Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log/addon.py): setting the Python path to /Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python26.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.6:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-dynload:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages/PIL
11:28:30 T:123145305600000   DEBUG: CPythonInvoker(34, /Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log/addon.py): entering source directory /Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log
11:28:30 T:123145305600000   DEBUG: CPythonInvoker(34, /Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log/addon.py): instantiating addon using automatically obtained id of "script.xbmc.debug.log" dependent on version 2.12.0 of the xbmc.python api
11:28:30 T:123145305600000  NOTICE: Kodi Log Uploader: started
11:28:30 T:123145305600000  NOTICE: Kodi Log Uploader: settings: len(email)=21
11:28:30 T:123145305600000  NOTICE: Kodi Log Uploader: settings: skip_oldlog=True
11:28:30 T:123145305600000   DEBUG: LocalizeStrings: no strings.po file exist at /Users/ChrisWalter/Library/Application Support/Kodi/addons/script.xbmc.debug.log/resources/language/English, fallback to strings.xml
11:28:30 T:140735198531584   DEBUG: ------ Window Init (DialogYesNo.xml) ------
11:28:32 T:140735198531584   DEBUG: ProcessMouse: trying mouse action leftclick
11:28:32 T:140735198531584   DEBUG: ------ Window Deinit (DialogYesNo.xml) ------
11:28:32 T:123145305600000  NOTICE: Kodi Log Uploader: reading log...

**Comment by brianhornsby** [comment]
Don't use SuperRepo.
